In [61]:
import os
import pandas as pd

data = []
for i in range(1, 14):
    folder_path = '/content/drive/MyDrive/ProjectData/s' + str(i) + '/txt/'
    for file_name in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file_name)
        with open(file_path, "r") as file:
            text = file.read()
            data.append({'Path': file_path, 'Text': text})

df = pd.DataFrame(data)
print(df)

                                                  Path  \
0     /content/drive/MyDrive/ProjectData/s1/txt/p1.txt
1     /content/drive/MyDrive/ProjectData/s1/txt/p2.txt
2     /content/drive/MyDrive/ProjectData/s1/txt/p3.txt
3     /content/drive/MyDrive/ProjectData/s1/txt/p4.txt
4     /content/drive/MyDrive/ProjectData/s1/txt/p5.txt
..                                                 ...
101  /content/drive/MyDrive/ProjectData/s13/txt/p4.txt
102  /content/drive/MyDrive/ProjectData/s13/txt/p5.txt
103  /content/drive/MyDrive/ProjectData/s13/txt/p6.txt
104  /content/drive/MyDrive/ProjectData/s13/txt/p7.txt
105  /content/drive/MyDrive/ProjectData/s13/txt/p8.txt

                                                  Text
0    Hail Durga, Ma Tara, destroyer of sorrows.\nIn...
1    One day, the goddess Durga bestowed her grace\...
2    Shouting “Hail Durga,” Srimonto boarded the bo...
3    Finally, the boat docked at Ratnamala quay to ...
4    The king Shalbahon was seated on a jewelled th...
..                                                 ...
101  How beautiful the deer looked as it danced in ...
102  The (dying) deer then began to cry out loud \n...
103  From under the shade of a banyan tree, Ravana ...
104  And disgorged the chariot he had swallowed.\nW...
105  Speaking tenderly, Ramachandra looked at the (...

[106 rows x 2 columns]

In [62]:
df = df.drop("Path", axis=1)

In [63]:
df

                                                  Text
0    Hail Durga, Ma Tara, destroyer of sorrows.\nIn...
1    One day, the goddess Durga bestowed her grace\...
2    Shouting “Hail Durga,” Srimonto boarded the bo...
3    Finally, the boat docked at Ratnamala quay to ...
4    The king Shalbahon was seated on a jewelled th...
..                                                 ...
101  How beautiful the deer looked as it danced in ...
102  The (dying) deer then began to cry out loud \n...
103  From under the shade of a banyan tree, Ravana ...
104  And disgorged the chariot he had swallowed.\nW...
105  Speaking tenderly, Ramachandra looked at the (...

[106 rows x 1 columns]

In [64]:
pip install pillow

Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (9.4.0)

In [65]:
import os
import pandas as pd
from PIL import Image
import numpy as np

data = []

for i in range(1, 14):
    img_folder_path = '/content/drive/MyDrive/ProjectData/s' + str(i) + '/img/'
    for file_name in os.listdir(img_folder_path):
        file_path = os.path.join(img_folder_path, file_name)

        img = Image.open(file_path)

        img_array = np.array(img)

        data.append({'Path': file_path, 'Image': img_array})

df2 = pd.DataFrame(data)

In [66]:
df2 = df2.drop("Path", axis=1)

In [68]:
df2

                                                 Image
0    [[[124, 129, 133], [92, 97, 93], [101, 103, 90...
1    [[[108, 133, 91], [100, 124, 74], [132, 150, 1...
2    [[[37, 50, 43], [46, 58, 56], [46, 57, 59], [5...
3    [[[68, 64, 55], [74, 70, 61], [72, 68, 59], [6...
4    [[[156, 153, 102], [33, 29, 17], [53, 52, 58],...
..                                                 ...
101  [[[0, 1, 5], [1, 2, 6], [2, 3, 8], [2, 3, 8], ...
102  [[[3, 2, 7], [4, 3, 9], [4, 3, 11], [4, 2, 13]...
103  [[[0, 1, 0], [3, 1, 4], [0, 1, 4], [0, 2, 11],...
104  [[[2, 0, 5], [5, 3, 8], [8, 6, 11], [8, 6, 9],...
105  [[[1, 1, 3], [1, 0, 5], [1, 0, 5], [1, 0, 5], ...

[106 rows x 1 columns]

In [69]:
df.reset_index(drop=True, inplace=True)

In [70]:
df.rename(columns={'index': 'index'}, inplace=True)

In [71]:
df.columns

Index(['Text'], dtype='object')

In [72]:
df2.reset_index(drop=True, inplace=True)

In [73]:
df2.columns

Index(['Image'], dtype='object')

In [74]:
merged_df = pd.merge(df, df2, left_index=True, right_index=True)

In [75]:
merged_df

,Text,Image
0,"Hail Durga, Ma Tara, destroyer of sorrows.\nIn...","[[[124, 129, 133], [92, 97, 93], [101, 103, 90..."
1,"One day, the goddess Durga bestowed her grace\...","[[[108, 133, 91], [100, 124, 74], [132, 150, 1..."
2,"Shouting “Hail Durga,” Srimonto boarded the bo...","[[[37, 50, 43], [46, 58, 56], [46, 57, 59], [5..."
3,"Finally, the boat docked at Ratnamala quay to ...","[[[68, 64, 55], [74, 70, 61], [72, 68, 59], [6..."
4,The king Shalbahon was seated on a jewelled th...,"[[[156, 153, 102], [33, 29, 17], [53, 52, 58],..."
...,...,...
101,How beautiful the deer looked as it danced in ...,"[[[0, 1, 5], [1, 2, 6], [2, 3, 8], [2, 3, 8], ..."
102,The (dying) deer then began to cry out loud \n...,"[[[3, 2, 7], [4, 3, 9], [4, 3, 11], [4, 2, 13]..."
103,"From under the shade of a banyan tree, Ravana ...","[[[0, 1, 0], [3, 1, 4], [0, 1, 4], [0, 2, 11],..."
104,And disgorged the chariot he had swallowed.\nW...,"[[[2, 0, 5], [5, 3, 8], [8, 6, 11], [8, 6, 9],..."
105,"Speaking tenderly, Ramachandra looked at the (...","[[[1, 1, 3], [1, 0, 5], [1, 0, 5], [1, 0, 5], ..."

In [76]:
merged_df.to_csv('Trainingdata-I.csv', index=False)